/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/aadhaarVerication`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/BankVerificationBusiness`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/BusinessDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/company-gst`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/fssai`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/next-step`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/pan-details`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/StoreDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/vendor-gst`; params?: Router.UnknownInputParams; } | { pathname: `/company/BankVerification`; params?: Router.UnknownInputParams; } | { pathname: `/seller_login`; params?: Router.UnknownInputParams; } | { pathname: `/seller_login/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/aadhaarVerication`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/BankVerificationBusiness`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/BusinessDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/company-gst`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/fssai`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/next-step`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/pan-details`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/StoreDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/Business_details/vendor-gst`; params?: Router.UnknownOutputParams; } | { pathname: `/company/BankVerification`; params?: Router.UnknownOutputParams; } | { pathname: `/seller_login`; params?: Router.UnknownOutputParams; } | { pathname: `/seller_login/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Business_details/aadhaarVerication${`?${string}` | `#${string}` | ''}` | `/Business_details/BankVerificationBusiness${`?${string}` | `#${string}` | ''}` | `/Business_details/BusinessDetails${`?${string}` | `#${string}` | ''}` | `/Business_details/company-gst${`?${string}` | `#${string}` | ''}` | `/Business_details/fssai${`?${string}` | `#${string}` | ''}` | `/Business_details/next-step${`?${string}` | `#${string}` | ''}` | `/Business_details/pan-details${`?${string}` | `#${string}` | ''}` | `/Business_details/StoreDetails${`?${string}` | `#${string}` | ''}` | `/Business_details/vendor-gst${`?${string}` | `#${string}` | ''}` | `/company/BankVerification${`?${string}` | `#${string}` | ''}` | `/seller_login${`?${string}` | `#${string}` | ''}` | `/seller_login/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/aadhaarVerication`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/BankVerificationBusiness`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/BusinessDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/company-gst`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/fssai`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/next-step`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/pan-details`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/StoreDetails`; params?: Router.UnknownInputParams; } | { pathname: `/Business_details/vendor-gst`; params?: Router.UnknownInputParams; } | { pathname: `/company/BankVerification`; params?: Router.UnknownInputParams; } | { pathname: `/seller_login`; params?: Router.UnknownInputParams; } | { pathname: `/seller_login/register`; params?: Router.UnknownInputParams; };
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/company/Business_details`; params?: Router.UnknownInputParams; } | { pathname: `/company/GSTVerfication`; params?: Router.UnknownInputParams; } | { pathname: `/company/PANVerification`; params?: Router.UnknownInputParams; } | { pathname: `/types/react-native-check-box.d`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/company/Business_details`; params?: Router.UnknownOutputParams; } | { pathname: `/company/GSTVerfication`; params?: Router.UnknownOutputParams; } | { pathname: `/company/PANVerification`; params?: Router.UnknownOutputParams; } | { pathname: `/types/react-native-check-box.d`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/company/Business_details${`?${string}` | `#${string}` | ''}` | `/company/GSTVerfication${`?${string}` | `#${string}` | ''}` | `/company/PANVerification${`?${string}` | `#${string}` | ''}` | `/types/react-native-check-box.d${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/company/Business_details`; params?: Router.UnknownInputParams; } | { pathname: `/company/GSTVerfication`; params?: Router.UnknownInputParams; } | { pathname: `/company/PANVerification`; params?: Router.UnknownInputParams; } | { pathname: `/types/react-native-check-box.d`; params?: Router.UnknownInputParams; };
    }
  }
}
